apiVersion: v1
kind: Service
metadata:
  name: dev-svc-kubepoc
  labels:
    app: svc-kubepoc
    targetEnvironment: dev
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: container-kubepoc
    targetEnvironment: dev
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: dev-pod-kubepoc
  labels:
    app: pod-kubepoc
    targetEnvironment: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: container-kubepoc
        targetEnvironment: dev
    spec:
      containers:
      - name: dev-conatiner-kubepoc
        image: devintegrationsdccr.azurecr.io/dev-kubepoc      
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred